import { useNavigate } from 'react-router-dom';

export default function TermsPage() {
  const navigate = useNavigate();
  return (
    <div style={{ minHeight: '100vh', background: '#0c0c10', padding: '40px 20px' }}>
      <button onClick={() => navigate(-1)} style={{ color: '#e8556a', background: 'none', border: 'none', cursor: 'pointer', marginBottom: '20px', fontSize: '14px' }}>← Back</button>
      <div style={{ maxWidth: '800px', margin: '0 auto', background: '#ffffff', borderRadius: '12px', padding: '40px', color: '#333', fontFamily: 'Arial, sans-serif', fontSize: '14px', lineHeight: '1.7' }}>
        <h1 style={{ fontSize: '26px', fontWeight: 'bold' }}>TERMS AND CONDITIONS</h1>
        <p style={{ color: '#595959' }}>Last updated: June 06, 2026</p>

        <h2>1. AGREEMENT TO TERMS</h2>
        <p>These Terms and Conditions constitute a legally binding agreement between you and DATEOS LLC ("we," "us," or "our"), doing business as DateOS, governing your access to and use of the DateOS website at dateos.io. By accessing or using our Services, you agree to be bound by these Terms.</p>

        <h2>2. SERVICES</h2>
        <p>DateOS is an AI-powered date night planning web application. Users enter their city, vibe, budget, and occasion and receive AI-generated date night plans including venue suggestions, timing, dress code suggestions, and insider tips. All plans are generated using artificial intelligence and are intended for inspiration purposes only. We do not guarantee the accuracy, availability, or quality of any recommended venue.</p>

        <h2>3. FREE TIER AND PAID PLANS</h2>
        <p>Users receive 2 free plans per month. Additional plans require payment via one of our paid tiers: Single Plan ($4.99 one-time), Pro Monthly ($19.99/month), or Pro Annual ($179/year). All payments are processed by Stripe. Subscriptions renew automatically unless cancelled.</p>

        <h2>4. CANCELLATIONS AND REFUNDS</h2>
        <p>You may cancel your subscription at any time by contacting us at hello@dateos.io. Refund requests are handled on a case-by-case basis. We reserve the right to approve or deny refund requests at our discretion.</p>

        <h2>5. AI-GENERATED CONTENT</h2>
        <p>All date plans are generated by artificial intelligence. DateOS does not verify the current operating status, hours, pricing, or availability of any recommended venue. You are responsible for independently verifying all recommendations before making reservations or purchases.</p>

        <h2>6. PROHIBITED ACTIVITIES</h2>
        <p>You agree not to: use the Services for any unlawful purpose; attempt to bypass or circumvent any payment or access controls; reverse engineer or copy any part of the platform; or use automated tools to scrape or extract content.</p>

        <h2>7. LIMITATION OF LIABILITY</h2>
        <p>To the maximum extent permitted by law, DATEOS LLC's total liability to you for any claim arising from your use of the Services shall not exceed the amount you paid us in the 6 months preceding the claim.</p>

        <h2>8. DISCLAIMER OF WARRANTIES</h2>
        <p>The Services are provided "as is" without warranties of any kind. We do not warrant that the Services will be uninterrupted, error-free, or that any specific results will be obtained from use of the Services.</p>

        <h2>9. GOVERNING LAW</h2>
        <p>These Terms are governed by the laws of the State of New York. Any disputes shall be resolved through informal negotiation first, followed by binding arbitration in New York County, New York.</p>

        <h2>10. CHANGES TO TERMS</h2>
        <p>We reserve the right to update these Terms at any time. Users will be notified at least 30 days before changes take effect. Continued use of the Services after changes constitutes acceptance of the new Terms.</p>

        <h2>11. CONTACT</h2>
        <p>DATEOS LLC<br/>hello@dateos.io<br/>418 Broadway #4618, Albany, NY 12207</p>
      </div>
    </div>
  );
}
